#include "ps2_transport.h"

#include <stddef.h>

#include "hardware/gpio.h"
#include "hardware/pio.h"
#include "pico/platform.h"   // __time_critical_func, count_of

#include "psxSPI.pio.h"      // generated by pico_generate_pio_header:
                             // *_program, *_program_init, read/write_byte_blocking, PIN_*

// pio0 is used for the PS2 bus; the cyw43 wireless driver uses its own PIO.
static uint sm_cmd_reader;
static uint sm_dat_writer;
static uint off_cmd_reader;
static uint off_dat_writer;
static void (*s_sel_hook)(void);

uint8_t ps2_recv_cmd(void) {
    return read_byte_blocking(pio0, sm_cmd_reader);
}

void ps2_send(uint8_t byte) {
    write_byte_blocking(pio0, sm_dat_writer, byte);
}

bool ps2_try_recv_cmd(uint8_t *out) {
    if (pio_sm_is_rx_fifo_empty(pio0, sm_cmd_reader))
        return false;
    *out = read_byte_blocking(pio0, sm_cmd_reader);  // non-empty: will not block
    return true;
}

bool ps2_try_send(uint8_t byte) {
    if (pio_sm_is_tx_fifo_full(pio0, sm_dat_writer))
        return false;
    write_byte_blocking(pio0, sm_dat_writer, byte);  // not full: will not block
    return true;
}

void __time_critical_func(ps2_restart_pio)(void) {
    const uint32_t mask = (1u << sm_cmd_reader) | (1u << sm_dat_writer);
    pio_set_sm_mask_enabled(pio0, mask, false);
    pio_restart_sm_mask(pio0, mask);
    pio_sm_exec(pio0, sm_cmd_reader, pio_encode_jmp(off_cmd_reader));
    pio_sm_exec(pio0, sm_dat_writer, pio_encode_jmp(off_dat_writer));
    pio_sm_clear_fifos(pio0, sm_cmd_reader);
    pio_sm_drain_tx_fifo(pio0, sm_dat_writer);  // drain (not clear) so the OSR empties too
    pio_enable_sm_mask_in_sync(pio0, mask);
}

// SEL rising edge == console deselected == end of transaction. Re-sync the SMs
// and let the device layer reset core1 so the next transaction parses cleanly.
static void __time_critical_func(sel_isr)(uint gpio, uint32_t events) {
    if (gpio != PIN_SEL || !(events & GPIO_IRQ_EDGE_RISE))
        return;
    ps2_restart_pio();
    if (s_sel_hook)
        s_sel_hook();
}

void ps2_transport_set_sel_hook(void (*hook)(void)) {
    s_sel_hook = hook;
}

void ps2_transport_enable_sel(bool enabled) {
    gpio_set_irq_enabled(PIN_SEL, GPIO_IRQ_EDGE_RISE, enabled);
}

void ps2_transport_init(void) {
    const uint pins[] = {PIN_DAT, PIN_CMD, PIN_SEL, PIN_CLK, PIN_ACK};
    for (size_t i = 0; i < count_of(pins); i++) {
        gpio_set_dir(pins[i], GPIO_IN);
        gpio_disable_pulls(pins[i]);
    }

    sm_cmd_reader = pio_claim_unused_sm(pio0, true);
    sm_dat_writer = pio_claim_unused_sm(pio0, true);
    off_cmd_reader = (uint)pio_add_program(pio0, &cmd_reader_program);
    off_dat_writer = (uint)pio_add_program(pio0, &dat_writer_program);
    cmd_reader_program_init(pio0, sm_cmd_reader, off_cmd_reader);
    dat_writer_program_init(pio0, sm_dat_writer, off_dat_writer);

    // Fast, strong DAT drive for a clean falling edge into the console input.
    gpio_set_slew_rate(PIN_DAT, GPIO_SLEW_RATE_FAST);
    gpio_set_drive_strength(PIN_DAT, GPIO_DRIVE_STRENGTH_12MA);

    // Register the SEL-rising ISR; the lifecycle enables it on connect. The SDK
    // shared handler acknowledges the IRQ for us (no manual iobank0 write).
    gpio_set_irq_enabled_with_callback(PIN_SEL, GPIO_IRQ_EDGE_RISE, false, sel_isr);
}
